#!/usr/bin/env bash
set -e

if [ -f /usr/bin/php8.1 ]; then

    sudo update-alternatives --set php /usr/bin/php8.1

    if [ -f /usr/bin/php7.4 ]; then sudo a2dismod php7.4; fi
    if [ -f /usr/bin/php8.2 ]; then sudo a2dismod php8.2; fi
    if [ -f /usr/bin/php8.3 ]; then sudo a2dismod php8.3; fi
    if [ -f /usr/bin/php8.4 ]; then sudo a2dismod php8.4; fi

    sudo a2enmod php8.1

    sudo service apache2 restart
else
    echo "PHP 8.1 is not installed."
    exit 1
fi
